name: Build

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        build_type: [Release]

    steps:      
      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          
      - name: Install meson and ninja
        run: |
          python -m pip install --upgrade pip
          pip install meson ninja

      - name: Install dependencies (ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo -E apt-get -yq install ninja-build gcc nasm
          
      - name: Install dependencies (mac)
        if: matrix.os == 'macos-latest'
        run: |
          brew install -q ninja nasm
          
      - uses: actions/checkout@v4
      - name: Build glib
        run: |
          meson setup build --prefix $PWD/install -Dtests=false
          meson install -C build
